CREATE TABLE linguagens (
  id SERIAL PRIMARY KEY,
  nome VARCHAR(255)
);

INSERT INTO linguagens(ID,NOME) VALUES (1, 'JAVA');
INSERT INTO linguagens(ID,NOME) VALUES (2, 'C#');
INSERT INTO linguagens(ID,NOME) VALUES (3, 'JAVASCRIPT');
INSERT INTO linguagens(ID,NOME) VALUES (4, 'PYTHON');
INSERT INTO linguagens(ID,NOME) VALUES (5, 'GO');